-- CORE Fitness application schema for Supabase PostgreSQL.
-- The Node backend connects with the database role from DATABASE_URL.
-- RLS is enabled without public policies so browser clients cannot access
-- application data directly through Supabase's public Data API.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  created_at text not null
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at text not null,
  created_at text not null
);

create table if not exists public.profiles (
  user_id bigint primary key references public.users(id) on delete cascade,
  name text not null,
  height text not null,
  weight text not null,
  age text not null,
  gender text not null check (gender in ('male', 'female')),
  goal text not null check (goal in ('lose_weight', 'gain_muscle', 'maintain', 'endurance')),
  target_weight text not null,
  workouts_per_week integer not null,
  updated_at text not null
);

create table if not exists public.checkins (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  checkin_date text not null,
  created_at text not null,
  unique (user_id, checkin_date)
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  calories integer not null,
  price_cents integer not null,
  image_url text not null,
  description text not null,
  protein integer not null,
  active integer not null default 1
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  menu_item_id bigint references public.menu_items(id),
  calorie_target integer not null,
  notes text not null default '',
  status text not null default 'received',
  total_cents integer not null default 0,
  created_at text not null
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  topic text not null check (topic in ('Training', 'Nutrition')),
  author_name text not null,
  avatar text not null,
  body text not null,
  image_url text,
  base_likes integer not null default 0,
  comments_count integer not null default 0,
  created_at text not null
);

create table if not exists public.post_likes (
  user_id bigint not null references public.users(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  created_at text not null,
  primary key (user_id, post_id)
);

create index if not exists sessions_user_id_idx on public.sessions(user_id);
create index if not exists sessions_expires_at_idx on public.sessions(expires_at);
create index if not exists checkins_user_id_idx on public.checkins(user_id);
create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists post_likes_post_id_idx on public.post_likes(post_id);

alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.profiles enable row level security;
alter table public.checkins enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
